title: CE/CCE 2025–2026 de Stanislas – Page personnelle (Non officiel)
description: Ce site a pour objectif de partager, en toute transparence, mes notes de travail, comptes rendus personnels et initiatives en tant qu’élu du CE/CCE pour l’année 2025–2026. Les informations publiées ici ne constituent pas des communications officielles du Collège Stanislas.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
## from dinky github 
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
