title: CE/CCE 2025–2026 de Stanislas – Page personnelle (Non officiel)
description: Notes personnelles d’un élu CE/CCE pour 2025–2026 — contenu non officiel.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
## from dinky github 
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
